### ISSUE TITLE
EmployeePayslip

### ISSUE THREAD

**Issue by zamashange** [boniface/hashwork#27]
Update Domain

**Comment by nkosy** [comment]
I modified this file and commited to the master accidentally The class is incomplete now my work has been merged with the master and I am afraid to modify the file cause it might cause conflicts later on. Please advise. Thank you

**Comment by boniface** [comment]
work from a fork and not master

**Comment by nkosy** [comment]
I am now working from a fork. Now I have 1 question. Can I go ahead & modify  the class even though my former changes have been merged alredy to the master?

**Comment by boniface** [comment]
Yes you can and create a pull request

**Comment by zamashange** [comment]
object updated & completed
